--- # Let's deploy the frontend!
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend-toy-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-toy-app
  template:
    metadata:
      labels:
        app: frontend-toy-app
    spec:
      containers:
      - name: frontend
        image: ghcr.io/hamada-distributed/k8s-toyapp:frontend
        command: [ "bash", "-c", "python3 -m http.server 2>&1" ]
        ports:
          - containerPort: 8000
