name: build backend image

on:
  workflow_dispatch:
  push:
    paths:
      - 'backend/**'
    branches:
      - main

jobs:
  push:
    name: "backend:build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/hamada-distributed/k8s-toyapp:backend
