name: build frontend image

on:
  workflow_dispatch:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yaml'
    branches:
      - main

jobs:
  push:
    name: "frontend:build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          platforms: linux/arm64,linux/amd64
          push: true
          tags: |
            ghcr.io/hamada-distributed/k8s-toyapp:frontend
